import {
	allImagesToSerializable,
	SPEC_COMMENTS,
	SPEC_FEEDBACK,
	SPEC_FIGMA,
	SPEC_FINAL_1,
	SPEC_FINAL_2,
	SPEC_FINAL_3,
	SPEC_FINAL_4,
	SPEC_FINAL_5,
	SPEC_FINAL_6,
	SPEC_PLUGIN_SCREENSHOT,
	SPEC_FUTURE,
} from '$lib/images';

export const load = async () => {
	return await allImagesToSerializable({
		SPEC_FIGMA,
		SPEC_COMMENTS,
		SPEC_FINAL_1,
		SPEC_FINAL_2,
		SPEC_FINAL_3,
		SPEC_FINAL_4,
		SPEC_FINAL_5,
		SPEC_FINAL_6,
		SPEC_FEEDBACK,
		SPEC_PLUGIN_SCREENSHOT,
		SPEC_FUTURE,
	});
};
