import {
	allImagesToSerializable,
	POLICYME_DESKTOP_1,
	POLICYME_DESKTOP_2,
	POLICYME_DESKTOP_3,
	POLICYME_INTERVIEW_1,
	POLICYME_INTERVIEW_2,
	POLICYME_MOBILE_1,
	POLICYME_MOBILE_2,
	POLICYME_MOBILE_3,
	POLICYME_PREVIEW,
	POLICYME_PROBLEM,
	POLICYME_DESIGN_ELEMENTS,
	POLICYME_IMPACT,
	POLICYME_DESIGN_SYSTEM,
} from '$lib/images';

export const load = async () => {
	const images = {
		POLICYME_PREVIEW,
		POLICYME_PROBLEM,
		POLICYME_INTERVIEW_1,
		POLICYME_INTERVIEW_2,
		POLICYME_MOBILE_1,
		POLICYME_MOBILE_2,
		POLICYME_MOBILE_3,
		POLICYME_DESKTOP_1,
		POLICYME_DESKTOP_2,
		POLICYME_DESKTOP_3,
		POLICYME_DESIGN_ELEMENTS,
		POLICYME_IMPACT,
		POLICYME_DESIGN_SYSTEM,
	};
	return await allImagesToSerializable(images);
};
